inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/GlobalVars:
  Exclude:
    - test/ruby_memcheck/ext/extconf.rb

Layout/CommentIndentation:
  AllowForAlignment: true
