name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { ruby: '2.7', allowed-failure: false }
          - { ruby: '3.0', allowed-failure: false }
          - { ruby: '3.1', allowed-failure: false }
          - { ruby: '3.2', allowed-failure: false }
          - { ruby: ruby-head, allowed-failure: false }
    name: ruby ${{ matrix.entry.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - run: sudo apt-get install -y valgrind
      - run: bundle install --jobs=3 --retry=3
      - run: bundle exec rake
        continue-on-error: ${{ matrix.entry.allowed-failure }}
